export interface mural {
    name: string,
    boroughId: number,
    artistId: number,
    year: number,
    city: string,
    coordinates: any,
    assistants: string[],
    partners: string[],
    description: string,
    socialMedia: string[],
    address: string,
    neighbourhood: string,
    imgURLs: string,
  }